apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless-cluster-ip
  namespace: {{ .Values.common.namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-pod
  ports:
    - port: 6379
      targetPort: 6379