apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-stateful-set
  namespace: {{ .Values.common.namespace }}
spec:
  serviceName: {{ .Chart.Name }}-headless-cluster-ip
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: {{ .Values.statefulSet.image.repository }}:{{ .Values.statefulSet.image.tag }}
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: {{ .Chart.Name }}-pvc
              mountPath: {{ .Values.statefulSet.volumeMounts.mountPath }}
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: {{ .Chart.Name }}-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.statefulSet.pvc.storage }}