FROM liquibase:4.30.0-alpine

COPY ./src/main/resources/db/changelog/ /liquibase/changelog/

ENTRYPOINT ["liquibase", "update", "--driver=org.postgresql.Driver", "--changeLogFile=/liquibase/changelog/db.changelog-master.yaml"]