name: Java CI
run-name: ${{ github.ref_name }}-${{ github.actor }}

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '23'

jobs:
  java-ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'adopt'
          cache: gradle

      - name: Checkstyle check
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon

      - name: Test with Gradle
        run: ./gradlew test --no-daemon

      - name: Upload Java artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: |
            . 
            !.infrastructure/**

      - name: Upload Docker artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-artifacts
          path: |
            .infrastructure/docker/**

      - name: Upload Helm artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-artifacts
          path: |
            .infrastructure/booking-service/**