apiVersion: v1
kind: Secret
metadata:
    name: {{ .Chart.Name }}-application-secret
    namespace: {{ .Values.common.namespace }}
type: Opaque
data:
  {{- range $k, $v := .Values.applicationSecret }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}