apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.common.namespace }}
spec:
  replicas: {{ .Values.bookingService.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.bookingService.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.bookingService.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-pod
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.bookingService.image.repository }}:{{ .Values.bookingService.image.tag }}
          ports:
              - containerPort: 8080
          startupProbe:
            httpGet:
              port: 8080
              path: /api/health/startup
            failureThreshold: 5
            initialDelaySeconds: 40
            periodSeconds: 20
            successThreshold: 1
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/actuator/health/liveness
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/actuator/health/readiness
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 3
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: {{ .Values.bookingService.applicationYmlMountPath }}
              name: application-config
              subPath: application.yml
          env:
            - name: SPRING_CONFIG_LOCATION
              value: {{ .Values.bookingService.applicationYmlMountPath }}
            {{- range $k, $v := .Values.applicationSecret }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  key: {{ $k }}
                  name: {{ $.Chart.Name }}-application-secret
            {{- end }}
      {{- if eq .Values.global.environment "local" }}
      imagePullSecrets:
        - name: ecr-secret
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Chart.Name }}-pod
      volumes:
        - name: application-config
          configMap:
            name: {{ .Chart.Name }}-application-config