{{- if eq .Values.common.environment "local" }}
apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  namespace: {{ .Values.common.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"AWS\",\"password\":\"%s\",\"auth\":\"%s\"}}}" "578748851450.dkr.ecr.eu-central-1.amazonaws.com" .Values.ecr.password (printf "AWS:%s" .Values.ecr.password | b64enc) | b64enc }}
{{- end }}