apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-hpa
  namespace: {{ .Values.common.namespace }}
spec:
  maxReplicas: {{ .Values.bookingService.hpa.maxReplicas }}
  minReplicas: {{ .Values.bookingService.hpa.minReplicas }}
  scaleTargetRef:
    kind: Deployment
    name: {{ .Chart.Name }}-deployment
    apiVersion: apps/v1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.bookingService.hpa.cpu.averageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.bookingService.hpa.memory.averageUtilization }}