apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.common.namespace }}
  annotations:
    cert-manager.io/issuer: {{ .Chart }}-letsencrypt-cluster-issuer
spec:
  tls:
    - secretName: {{ .Chart.Name }}-tls
      hosts:
        - {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-cluster-ip
                port:
                  number: {{ .Values.clusterIp.port }}


