apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-viewer-cluster-role
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
      - services
      - endpoints
      - secrets
      - configmaps
      - deployments
    verbs:
      - get
      - list
      - watch