common:
  namespace: psql

statefulSet:
  liquibase:
    image:
      repository: 578748851450.dkr.ecr.eu-central-1.amazonaws.com/booking-liquibase
      tag: 1.1.0
  pvc:
    storage: 5Gi
  volumeMounts:
    mountPath: /var/lib/postgresql
  image:
    repository: postgres
    tag: 12-bookworm

db:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: booking