name: Docker CI
run-name: ${{ github.ref_name }}-${{ github.actor }}

on:
  workflow_call:
    inputs:
      docker-image:
        type: string
        required: true
      docker-file:
        type: string
        required: true

jobs:
  docker-ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Java artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-artifacts

      - uses: aws-actions/configure-aws-credentials@v4
        name: Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login

      - name: Build Liquibase Docker image
        run: |
          cd .infrastructure/docker
          docker build -t ${{ steps.ecr-login.outputs.registry }}/${{ inputs.docker-image }}:${{ github.sha }} ../../ -f ${{ inputs.docker-file }}
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ inputs.docker-image }}:${{ github.sha }}
