name: App Deployment
run-name: ${{ github.ref_name }}-${{ github.actor }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref_name }}-${{ github.actor }}

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  java-ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
          cache: gradle

      - name: Checkstyle check
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon

      - name: Test with Gradle
        run: ./gradlew test --no-daemon

